"""add_second_approver

Revision ID: bd391a506c42
Revises: e7c6fe80dc5f
Create Date: 2026-08-27 16:12:54.947227
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bd391a506c42'
down_revision: Union[str, None] = 'e7c6fe80dc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('requires_second_approver', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'requires_second_approver')
    # ### end Alembic commands ###
