"""Add embedding to decision

Revision ID: d7749d464f11
Revises: dea2c2ae0c37
Create Date: 2026-08-27 15:52:03.606006
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


revision: str = 'd7749d464f11'
down_revision: Union[str, None] = 'dea2c2ae0c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'embedding')
    # ### end Alembic commands ###
