"""initial_schema

Revision ID: dea2c2ae0c37
Revises: 
Create Date: 2026-08-26 16:57:52.935713
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dea2c2ae0c37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('drive', 'gmail', 'manual_upload', name='contractsource'), nullable=False),
    sa.Column('source_file_id', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'parse_failed', 'manual_review', 'scanning', name='contractstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_org_id'), 'contracts', ['org_id'], unique=False)
    op.create_table('usage_signals',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_users_count', sa.Integer(), nullable=True),
    sa.Column('seats_purchased', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('okta_mcp', 'manual', name='usagesignalsource'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_signals_org_id'), 'usage_signals', ['org_id'], unique=False)
    op.create_index(op.f('ix_usage_signals_vendor_name'), 'usage_signals', ['vendor_name'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'viewer', name='userrole'), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('mcp_tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'low_confidence', name='agentrunstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_contract_id'), 'agent_runs', ['contract_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('contract_clauses',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('price_escalation_pct', sa.Float(), nullable=True),
    sa.Column('contract_value_annual', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('raw_extraction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ambiguous_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_clauses_contract_id'), 'contract_clauses', ['contract_id'], unique=False)
    op.create_table('decisions',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Enum('cancel', 'renegotiate_seats', 'renew', 'manual_review', name='recommendedaction'), nullable=True),
    sa.Column('expected_impact_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', 'auto_approved', name='approvalstatus'), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_contract_id'), 'decisions', ['contract_id'], unique=False)
    op.create_table('mcp_connections',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_type', sa.Enum('google_drive', 'gmail', 'slack', 'okta', name='mcpservertype'), nullable=False),
    sa.Column('mcp_server_url', sa.String(length=512), nullable=True),
    sa.Column('auth_credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes_granted', sa.Text(), nullable=True),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'disconnected', name='mcpconnectionstatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_connections_org_id'), 'mcp_connections', ['org_id'], unique=False)
    op.create_table('actions',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('email_draft', 'slack_alert', 'task_created', 'cancellation_email_sent', 'renegotiation_email_sent', name='actiontype'), nullable=False),
    sa.Column('mcp_server_used', sa.String(length=64), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'cancelled', name='actionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_decision_id'), 'actions', ['decision_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'inconclusive', name='outcomeresult'), nullable=True),
    sa.Column('spend_delta_amount', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_decision_id'), 'outcomes', ['decision_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_decision_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_actions_decision_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_mcp_connections_org_id'), table_name='mcp_connections')
    op.drop_table('mcp_connections')
    op.drop_index(op.f('ix_decisions_contract_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_contract_clauses_contract_id'), table_name='contract_clauses')
    op.drop_table('contract_clauses')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_contract_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_signals_vendor_name'), table_name='usage_signals')
    op.drop_index(op.f('ix_usage_signals_org_id'), table_name='usage_signals')
    op.drop_table('usage_signals')
    op.drop_index(op.f('ix_contracts_org_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('organizations')
    # ### end Alembic commands ###
