"""add_org_settings

Revision ID: e7c6fe80dc5f
Revises: d7749d464f11
Create Date: 2026-08-27 16:06:07.743897
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7c6fe80dc5f'
down_revision: Union[str, None] = 'd7749d464f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_settings',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('approval_threshold_usd', sa.Float(), nullable=False),
    sa.Column('second_approver_threshold_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_settings')
    # ### end Alembic commands ###
